### PR TITLE
Add `exclude` option with wildcard matching on label names

### PR DESCRIPTION
**Pull request by citycide**
Add an `exclude` option that allows for preventing certain labels from being altered, for more granular control than `skip_delete` alone.

```yaml
exclude: 'area/*'
```

GitHub seems to only support passing strings so you can't pass a bare array, however multiple patterns can still be passed by surrounding a YAML string array with quotes:

```yaml
exclude: "['area/*', 'os/*']"
```

The matching is a simple wildcard pattern rather than full glob syntax &mdash; we're not matching paths. This is implemented using [matcher](https://github.com/sindresorhus/matcher).

The tests [can be seen here](https://github.com/citycide/ghaction-github-labeler/commit/2f729c3104298e24c2b83c70967b3477ab07addc/checks?check_suite_id=272573878).

```
🏃 Running GitHub Labeler
⚠️ Skipping update for 'bug' label. Same color and description
🚫️ Excluding 'enhancement' from update.
⚠️ Skipping update for 'good first issue' label. Same color and description
⚠️ Skipping update for 'help wanted' label. Same color and description
⚠️ Skipping update for 'invalid' label. Same color and description
⚠️ Skipping update for 'question' label. Same color and description
🚫️ Excluding 'wontfix' from rename.
🚫️ Excluding 'documentation' from deletion.
🚫️ Excluding 'duplicate' from deletion.
```

### CODE REVIEW

**Comment by crazy-max** [comment]
Awesome @citycide! Thanks for your contrib! :rocket:

**Comment by crazy-max** [comment]
Use `npm prune --production` before pushing next time ;)

**Comment by citycide** [comment]
@crazy-max sure thing - might be good then to have that in a contributing guide, and included or linked in the readme. I've never included `node_modules` in a repo before but I guess it's different for Actions.

**Comment by crazy-max** [comment]
> sure thing - might be good then to have that in a contributing guide, and included or linked in the readme.

I've added a [workflow](https://github.com/crazy-max/ghaction-github-labeler/blob/master/.github/workflows/uncommited.yml) to detect this behavior ;)
But yeah a contributing guide would be better :)

> I've never included node_modules in a repo before but I guess it's different for Actions.

Yes indeed, for actions `node_modules` is needed. Not really on `master` branch but I prefer to keep it to allow users to test an action on master.

**Pull request merged**
