### PR TITLE
feature: allow hash in color codes

### LINKED ISSUE #153: Allow hash in color codes
It would be awesome to allow configuring colors in `#112233` format, because it plays nicer with [IDE plugins](https://github.com/enyancc/vscode-ext-color-highlight) and makes previewing colors easier.
Screen Shot 2022-01-31 at 4 44 58 PM

### PR DESCRIPTION
**Pull request by davorpa**
Resolves #153

### CODE REVIEW

**Review by crazy-max — CHANGES_REQUESTED** [review]
Needs rebase

**Comment by crazy-max** [comment]
CI doesn't look happy about it :sweat_smile:

**Comment by davorpa** [comment]
> CI doesn't look happy about it 😅

What I need to run test on my machine? I'm running Windows and it seems that some config is missing (e.g. GITHUB_TOKEN) when I run `docker buildx bake validate` or `yarn test`

**Comment by crazy-max** [comment]
> > CI doesn't look happy about it 😅
> 
> What I need to run test on my machine? I'm running Windows and it seems that some config is missing (e.g. GITHUB_TOKEN) when I run `docker buildx bake validate` or `yarn test` even running over a clean master branch

Sorry for the delay, https://github.com/crazy-max/ghaction-github-labeler/pull/192 removes requirement for the github token. You can now just run `docker buildx bake test` or `yarn test`

**Review by crazy-max — CHANGES_REQUESTED** [review]
> > CI doesn't look happy about it 😅
> 
> What I need to run test on my machine? I'm running Windows and it seems that some config is missing (e.g. GITHUB_TOKEN) when I run `docker buildx bake validate` or `yarn test` even running over a clean master branch

Sorry for the delay, https://github.com/crazy-max/ghaction-github-labeler/pull/192 removes requirement for the github token. You can now just run `docker buildx bake test` or `yarn test`

**Pull request closed without merging**
